import { StyleSheet } from 'react-native';
import { theme } from '../../shared/config/theme';

const b = theme.business;

export const styles = StyleSheet.create({
  root: {
    flex: 1,
    flexDirection: 'row',
    backgroundColor: b.colors.background,
  },
  sidebar: {
    width: b.spacing.sidebarWidth,
    backgroundColor: b.colors.sidebar.background,
    padding: 24,
    minHeight: '100%',
  },
  logoArea: {
    paddingBottom: 32,
    paddingHorizontal: 4,
    paddingTop: 4,
  },
  logoImage: {
    height: 48,
    width: '100%',
    resizeMode: 'contain',
  },
  navList: {
    marginTop: 8,
    rowGap: 8,
  },
  navItem: {
    flexDirection: 'row',
    alignItems: 'center',
    columnGap: 12,
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderRadius: b.radius.pill,
  },
  navItemActive: {
    backgroundColor: b.colors.surface,
    ...b.shadows.soft,
  },
  navLabelActive: {
    fontSize: 15,
    fontWeight: '400' as const,
    fontFamily: b.typography.fontFamilySemiBold,
    color: b.colors.primary,
  },
  navLabelInactive: {
    fontSize: 15,
    fontWeight: '400' as const,
    fontFamily: b.typography.fontFamilySemiBold,
    color: b.colors.foreground,
    opacity: 0.7,
  },
  collapseBtn: {
    position: 'absolute',
    right: -14,
    top: 96,
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: b.colors.surface,
    borderWidth: 1,
    borderColor: b.colors.border,
    alignItems: 'center',
    justifyContent: 'center',
    ...b.shadows.soft,
  },
  content: {
    flex: 1,
  },
  topbar: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    paddingHorizontal: 40,
    paddingTop: 32,
    paddingBottom: 24,
    columnGap: 24,
    backgroundColor: b.colors.background,
  },
  topbarTitle: {
    fontSize: b.typography.title.fontSize,
    fontWeight: b.typography.title.fontWeight,
    fontFamily: b.typography.title.fontFamily,
    color: b.colors.foreground,
    letterSpacing: b.typography.letterSpacing.tight,
    lineHeight: b.typography.title.fontSize,
  },
  topbarSubtitle: {
    fontSize: b.typography.body.fontSize,
    fontWeight: b.typography.body.fontWeight,
    fontFamily: b.typography.fontFamily,
    color: b.colors.mutedForeground,
    marginTop: 8,
  },
  topbarRight: {
    flexDirection: 'row',
    alignItems: 'center',
    columnGap: 16,
    flexShrink: 1,
  },
  searchWrapper: {
    maxWidth: 420,
    flex: 1,
    height: 48,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: b.colors.surface,
    borderWidth: 1,
    borderColor: b.colors.border,
    borderRadius: b.radius.pill,
    paddingHorizontal: 20,
    ...b.shadows.soft,
  },
  searchInput: {
    flex: 1,
    marginLeft: 8,
    fontSize: 14,
    fontFamily: b.typography.fontFamily,
    color: b.colors.foreground,
  },
  userPill: {
    flexDirection: 'row',
    alignItems: 'center',
    columnGap: 12,
    backgroundColor: b.colors.surface,
    borderWidth: 1,
    borderColor: b.colors.border,
    borderRadius: b.radius.pill,
    paddingLeft: 6,
    paddingRight: 16,
    paddingVertical: 6,
    ...b.shadows.soft,
  },
  avatar: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: b.colors.foreground,
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarText: {
    color: b.colors.background,
    fontSize: 12,
    fontWeight: '400' as const,
    fontFamily: b.typography.fontFamilyBold,
  },
  userInfoBlock: {
    rowGap: 2,
  },
  userName: {
    fontSize: 14,
    fontWeight: '400' as const,
    fontFamily: b.typography.fontFamilySemiBold,
    color: b.colors.foreground,
  },
  userRoleText: {
    fontSize: 11,
    fontFamily: b.typography.fontFamily,
    color: b.colors.mutedForeground,
  },
  mainContent: {
    flex: 1,
    backgroundColor: b.colors.background,
  },
});
